[build]
  base = "apps/task-manager"
  command = "pnpm install && pnpm build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- apps/task-manager/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
